spring:
  # sql문 실행해주는 기능
  sql:
    init:
      mode: always
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${user_mail}
    password: ${user_ps}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          timeout: 5000

  datasource:
    master:
      url: ${master_DBurl}
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${DB_user}
      password: ${DB_ps}

    slave:
      url: ${slave_DBurl}
      driver-class-name: org.mariadb.jdbc.Driver
      username: ${DB_user}
      password: ${DB_ps}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  skey: ${jwt_key}
  expored : ${jwt_exp}